### ISSUE TITLE
Is the endpoint for searching products is still working?

### ISSUE THREAD

**Issue by uvulpos** [AdriDevelopsThings/rewe_rs#1]
Hi there,
I was trying based on your implementation to adapt your code into golang code, but I could not make my  query `https://mobile-api.rewe.de/api/v3/product-search?marketCode=<my-store-id>&objectsPerPage=250&page=1&searchTerm=K&serviceTypes=PICKUP` to work. I got a 400. Do I miss something? Could you verify your code base that it is still working?

**Comment by AdriDevelopsThings** [comment]
I tried if my code still works and the product search request seems to work. Did you forget to add the headers to your request (https://github.com/AdriDevelopsThings/rewe_rs/blob/main/src/product/search.rs#L23). The rewe api sometimes needs some of these headers.
